//Fetch Race list 
export const RACE_LIST_TOPPER_FETCH_ISPAGELOADING = "RACE_LIST_TOPPER_FETCH_ISPAGELOADING";
export const RACE_LIST_TOPPER_PAGE_SUCCESS = "RACE_LIST_TOPPER_PAGE_SUCCESS";
export const RACE_LIST_TOPPER_PAGE_ERROR = "RACE_LIST_TOPPER_PAGE_ERROR";

//Fetch Season Champion  
export const SEASON_CHAMPION_SUCCESS = "SEASON_CHAMPION_SUCCESS";