//Fetch champion list
export const CHAMPION_LIST_FETCH_ISPAGELOADING = "CHAMPION_LIST_FETCH_ISPAGELOADING";
export const CHAMPION_LIST_FETCH_PAGE_SUCCESS = "CHAMPION_LIST_FETCH_PAGE_SUCCESS";
export const CHAMPION_LIST_FETCH_PAGE_ERROR = "CHAMPION_LIST_FETCH_PAGE_ERROR";

//Query champion list
export const CHAMPION_LIST_ISQUERYING = "CHAMPION_LIST_ISQUERYING";
export const CHAMPION_LIST_QUERY_SUCCESS = "CHAMPION_LIST_QUERY_SUCCESS";
export const CHAMPION_LIST_LIST_QUERY_ERROR = "CHAMPION_LIST_LIST_QUERY_ERROR";